
(let Tuple/swap std/tuple/swap)
(let Tuple/map/fst std/tuple/map/fst)
(let Tuple/map/snd std/tuple/map/snd)
(let Tuple/map std/tuple/map)
(let Tuple/map/fst std/tuple/map/fst)
(let Tuple/map/snd std/tuple/map/snd)

(let Vector->Tuple (lambda fn1 fn2 xs (std/convert/vector->tuple xs fn1 fn2)))
(let Tuple/int/add std/tuple/int/add)
(let Tuple/int/sub std/tuple/int/sub)
(let Tuple/int/mul std/tuple/int/mul)
(let Tuple/int/div std/tuple/int/div)

(let Tuple/bool/eq? (lambda { a b } (=? a b)))
(let Tuple/int/eq? (lambda { a b } (= a b)))
(let Tuple/char/eq? (lambda { a b } (=# a b)))
(let Tuple/float/eq? (lambda { a b } (=. a b)))

(let Tuple/bool/not-eq? (lambda { a b } (not (=? a b))))
(let Tuple/int/not-eq? (lambda { a b } (not (= a b))))
(let Tuple/char/not-eq? (lambda { a b } (not (=# a b))))
(let Tuple/float/not-eq? (lambda { a b } (not (=. a b))))

(let Int->Alphabet std/convert/int->char/alphabet)

(let Integer->Chars std/convert/integer->string)
(let Integer->String std/convert/integer->string)
(let Float->Chars std/convert/float->string)
(let Float->String std/convert/float->string)

(let String->Vector (lambda ch xs (std/convert/string->vector xs ch)))
(let Vector->String (lambda ch xs (std/convert/vector->string xs ch)))
(let Chars->Integer std/convert/chars->integer)
(let String->Integer std/convert/chars->integer)
(let String->Float std/convert/chars->float)
(let Chars->Float std/convert/chars->float)
(let Integer->Bits std/convert/integer->bits)

(let Char->Digit std/convert/char->digit)
(let Digit->Char std/convert/digit->char)

(let Integer->Digits std/convert/integer->digits)
(let Digits->Chars std/convert/digits->chars)
(let Set->Vector std/convert/set->vector)
(let Vector->Set std/convert/vector->set)

(let Vector/equal? std/vector/equal?)

(let Set/size std/vector/flat/length)
(let Table/size std/vector/flat/length)

(let Set/new (lambda (std/vector/buckets 32)))
(let Table/new (lambda (std/vector/buckets 32)))

(let Set/intersection std/vector/hash/set/intersection)
(let Set/difference std/vector/hash/set/difference)
(let Set/xor std/vector/hash/set/xor)
(let Set/union std/vector/hash/set/union)
(let Set/add! (lambda item table (do (std/vector/hash/set/add! table item) nil)))
(let Set/remove! (lambda item table (do (std/vector/hash/set/remove! table item) nil)))
(let Set/has? (lambda item table (std/vector/hash/set/has? table item)))

(let Table/entries std/vector/tuple/hash/table/entries)
(let Table/keys std/vector/tuple/hash/table/keys)
(let Table/values std/vector/tuple/hash/table/values)

(let Set/values std/vector/flat-one)

(let Table/get (lambda key table (std/vector/tuple/hash/table/get table key)))
(let Table/get* (lambda key table (if (std/vector/tuple/hash/table/has? table key) { true [(snd (get (std/vector/tuple/hash/table/get table key)))] } { false [] })))

(let Table/has? (lambda key table (std/vector/tuple/hash/table/has? table key)))
(let Table/set! (lambda key value table (do (std/vector/tuple/hash/table/set! table key value) nil)))
(let Table/remove! (lambda key table (do (std/vector/tuple/hash/table/remove! table key) nil)))
(let Table/count std/vector/tuple/hash/table/count)

(let Table/drop! (lambda keys table (std/vector/tuple/hash/table/drop! table keys)))
(let Table/keep (lambda keys table (std/vector/tuple/hash/table/keep table keys)))
(let Table/omit (lambda keys table (std/vector/tuple/hash/table/omit table keys)))

(let Table/merge! std/vector/tuple/hash/table/merge!)
(let Table/merge std/vector/tuple/hash/table/merge)

(let Que/new std/vector/deque/new)
(let Que/empty? std/vector/deque/empty?)
(let Que/not-empty? std/vector/queue/not-empty?)
(let Que/empty! (lambda q (do (std/vector/deque/empty! q) nil)))
(let Que/enque! (lambda v xs(do (std/vector/queue/enqueue! xs v) nil)))
(let Que/deque! (lambda queue (do (std/vector/deque/tail! queue) nil)))
(let Que/peek std/vector/deque/first)
(let Que/push! (lambda v xs (do (std/vector/deque/append! xs v) nil)))
(let Que/pop! (lambda queue (do (std/vector/deque/head! queue) nil)))
(let Que/prepend! (lambda v xs (do (std/vector/deque/prepend! xs v) nil))) 
(let Que/first std/vector/deque/first)
(let Que/last std/vector/deque/last)
(let Que/tail! (lambda queue (do (std/vector/deque/tail! queue) nil)))
(let Que/append! (lambda v xs (do (std/vector/deque/append! xs v) nil)))

(let Vector->Que std/convert/vector->deque)
(let Que->Vector std/convert/deque->vector)
(let Que/get std/vector/deque/get)
(let Que/length std/vector/deque/length)
(let Que/at (lambda i xs (if (< i 0) (std/vector/deque/get xs (+ (length xs) i)) (std/vector/deque/get xs i))))


(let BigInt/add std/int/big/add)
(let BigInt/sub std/int/big/sub)
(let BigInt/mul std/int/big/mul)
(let BigInt/lte? std/int/big/less-or-equal?)
(let BigInt/gte? std/int/big/greater-or-equal?)
(let BigInt/lt? std/int/big/less-than?)
(let BigInt/gt? std/int/big/greater-than?)
(let BigInt/equal? std/int/big/equal?)
(let BigInt/div std/int/big/div)
(let BigInt/square std/int/big/square)
(let BigInt/div/floor std/int/big/floor/div)
(let BigInt/div/ceal std/int/big/ceil/div)
(let BigInt/sum std/vector/int/big/sum)
(let BigInt/product std/vector/int/big/product)
(let BigInt/new std/int/big/new)
(let BigInt/pow std/int/big/pow)
(let BigInt/expt std/int/big/expt)
(let BigInt/range std/vector/int/big/range)

(let Vector/push! std/vector/push!)
(let Vector/pop! std/vector/pop!)
(let Vector/last std/vector/last)
(let Vector/first std/vector/first)
(let Vector/pull! std/vector/pop-and-get!)
(let Vector/get std/vector/get)
(let Vector/set! std/vector/set!)
(let Vector/length std/vector/length)
(let Vector/append! (lambda x xs (std/vector/append! xs x)))
(let Vector/2d/set! std/vector/2d/int/set!)
(let Vector/2d/add std/vector/2d/int/add)
(let Vector/2d/sub std/vector/2d/int/sub)
(let Vector/2d/mul std/vector/2d/int/mul)
(let Vector/2d/div std/vector/2d/int/div)
(let Vector/2d/mag/sqrt std/vector/2d/int/mag/sqrt)
(let Vector/2d/mag std/vector/2d/int/mag)
(let Vector/2d/dot std/vector/2d/int/dot)
(let Vector/2d/cross std/vector/2d/int/cross)
(let Vector/2d/dist std/vector/2d/int/dist)
(let Vector/2d/norm std/vector/2d/int/normalize)
(let Vector/2d/limit std/vector/2d/int/limit)
(let Vector/2d/add! std/vector/2d/int/add!)
(let Vector/2d/sub! std/vector/2d/int/sub!)
(let Vector/2d/mul! std/vector/2d/int/mul!)
(let Vector/2d/div! std/vector/2d/int/div!)
(let Vector/2d/norm! std/vector/2d/int/normalize!)
(let Vector/2d/limit! std/vector/2d/int/limit!)
(let Vector/2d/mag! std/vector/2d/int/mag!)
(let Vector/3d/set! std/vector/3d/int/set!)
(let Vector/3d/add std/vector/3d/int/add)
(let Vector/3d/sub std/vector/3d/int/sub)
(let Vector/3d/mul std/vector/3d/int/mul)
(let Vector/3d/div std/vector/3d/int/div)
(let Vector/3d/mag/sqrt std/vector/3d/int/mag/sqrt)
(let Vector/3d/mag std/vector/3d/int/mag)
(let Vector/3d/dot std/vector/3d/int/dot)
(let Vector/3d/cross std/vector/3d/int/cross) 
(let Vector/3d/dist std/vector/3d/int/dist)
(let Vector/3d/norm std/vector/3d/int/normalize) 
(let Vector/3d/limit std/vector/3d/int/limit)
(let Vector/3d/add! std/vector/3d/int/add!)
(let Vector/3d/sub! std/vector/3d/int/sub!)
(let Vector/3d/mul! std/vector/3d/int/mul!)
(let Vector/3d/div! std/vector/3d/int/div!)
(let Vector/3d/norm! std/vector/3d/int/normalize!)
(let Vector/3d/limit! std/vector/3d/int/limit!)
(let Vector/3d/mag! std/vector/3d/int/mag!)


(let Vector/new (lambda fn n (std/vector/2d/fill n fn)))
(let Matrix/new (lambda fn w h (std/vector/3d/fill w h fn)))
(let String/equal? std/vector/char/equal?)
(let String/lte? std/vector/char/lesser-or-equal?)
(let String/gte? std/vector/char/greater-or-equal?)
(let String/lt? std/vector/char/lesser?)
(let String/gt? std/vector/char/greater?)